name: Deploy Dev

on:
  push:
    branches: [ master ]  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run script on server
        uses: appleboy/ssh-action@v1.0.3 
        with:
          host: ${{ secrets.DEPLOY_HOST }} 
          username: ${{ secrets.DEPLOY_USER }}  
          key: ${{ secrets.DEPLOY_KEY }} 
          script: | 
            cd
            bash server.sh
